### ISSUE TITLE
Cps counter

### ISSUE THREAD

**Issue by Moneyourself** [Scareships/Suggestions#2]
Idk but this the only client that I find that works so if u could make a cps counter that would be great. Maybe keystrokes too if u can. also rgb? maybe idk just a suggestion

**Comment by Moneyourself** [comment]
thx for reading

**Comment by jamsuwu** [comment]
> Idk but this the only client that I find that works so if u could make a cps counter that would be great. Maybe keystrokes too if u can. also rgb? maybe idk just a suggestion

i mean onix works, just sayin..

**Comment by Scareships** [comment]
yes, right now, the dll is getting dev. And yes there will be a CPS counter. Please stay patient
